### ISSUE TITLE
Final group capstone: set up your Kanban board 

### ISSUE THREAD

**Issue by Log-benjamin** [Log-benjamin/Wheels-4-Rent-backend#17]
## [Project requirements](https://github.com/microverseinc/curriculum-final-capstone/blob/main/projects/setup_kanban_board.md#project-requirements)

- We have prepared a [Kanban board](https://github.com/Log-benjamin/Wheels-4-Rent-backend/projects/1) for the Fullstack group project per the given project requirement.

## Team Members
1. [Emmanuel Kipngeno](https://github.com/kkmanuu?tab=repositories)
2. [kerlos bahaa](https://github.com/kerlos-bahaa?tab=repositories)
3. [Binyam Tegene](https://github.com/Log-benjamin?tab=repositories)

## Screenshot of the Kanban board

![Screenshot (153)](https://github.com/Log-benjamin/Wheels-4-Rent-backend/assets/97245616/fc50c624-f431-4dc6-8c29-a20a40f49d19)

**Comment by Meltrust** [comment]
Hi @Log-benjamin,

## Wow, you did it 🎉 
![Brilliant](https://media.giphy.com/media/d31w24psGYeekCZy/giphy.gif)

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

### To highlight

- All cards have descriptions, assignees, and are pointed according to spec✔️ 


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
